# CMake generated Testfile for 
# Source directory: /home/toshio/oyo-calamares/src/libcalamares
# Build directory: /home/toshio/oyo-calamares/obj-x86_64-linux-gnu/src/libcalamares
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(libcalamarestest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamarestest")
set_tests_properties(libcalamarestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;221;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresgeoiptest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamaresgeoiptest")
set_tests_properties(libcalamaresgeoiptest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;223;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamareslocaletest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamareslocaletest")
set_tests_properties(libcalamareslocaletest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;225;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresmodulesystemtest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamaresmodulesystemtest")
set_tests_properties(libcalamaresmodulesystemtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;227;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresnetworktest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamaresnetworktest")
set_tests_properties(libcalamaresnetworktest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;229;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespackagestest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamarespackagestest")
set_tests_properties(libcalamarespackagestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;231;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitiontest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamarespartitiontest")
set_tests_properties(libcalamarespartitiontest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;234;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitionkpmtest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamarespartitionkpmtest")
set_tests_properties(libcalamarespartitionkpmtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;239;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilstest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamaresutilstest")
set_tests_properties(libcalamaresutilstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;242;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilspathstest "/home/toshio/oyo-calamares/obj-x86_64-linux-gnu/libcalamaresutilspathstest")
set_tests_properties(libcalamaresutilspathstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/toshio/oyo-calamares/obj-x86_64-linux-gnu" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;123;add_test;/home/toshio/oyo-calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;244;calamares_add_test;/home/toshio/oyo-calamares/src/libcalamares/CMakeLists.txt;0;")
